exclude: Gemfile, Gemfile.lock, Rakefile, config.rb, sass
safe: false
server_port: 4000
url: http://localhost:4000
markdown: rdiscount
pygments: true
asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  gzip: false             # Default = false
caman:
  stable_version: 4.1.1
  cdn_version: 4.0.0

filters:
  - brightness
  - contrast
  - saturation
  - vibrance
  - exposure
  - hue
  - sepia
  - gamma
  - noise
  - clip
  - sharpen
  - stackBlur
filter_options:
  brightness:
    min: -100
    max: 100
    step: 1
  contrast:
    min: -100
    max: 100
    step: 1
  saturation:
    min: -100
    max: 100
    step: 1
  vibrance:
    min: -100
    max: 100
    step: 1
  exposure:
    min: -100
    max: 100
    step: 1
  hue:
    min: 0
    max: 100
    step: 1
  sepia:
    min: 0
    max: 100
    step: 1
  gamma:
    min: 0
    max: 10
    step: 0.1
  noise:
    min: 0
    max: 100
    step: 1
  clip:
    min: 0
    max: 100
    step: 1
  sharpen:
    min: 0
    max: 100
    step: 1
  stackBlur:
    min: 0
    max: 20
    step: 1

caman_presets:
  - vintage
  - lomo
  - clarity
  - sinCity
  - sunrise
  - crossProcess
  - orangePeel
  - love
  - grungy
  - jarques
  - pinhole
  - oldBoot
  - glowingSun
  - hazyDays
  - herMajesty
  - nostalgia
  - hemingway
  - concentrate
